name: Daily PvP Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run daily at 01:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us, eu, kr, tw]

    steps:
      # 1. full-depth checkout so we can switch branches
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0      # needed for git checkout later

      # 2. move onto the dev branch
      - name: Checkout dev branch
        run: git checkout dev

      # 3. set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp requests psutil

      # 4. run the sync *on the dev work-tree*
      - name: Run PvP Sync for ${{ matrix.region }}
        env:
          BLIZZARD_CLIENT_ID:     ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
          BLIZZARD_CLIENT_ID_EU:     ${{ secrets.BLIZZARD_CLIENT_ID_EU }}
          BLIZZARD_CLIENT_SECRET_EU: ${{ secrets.BLIZZARD_CLIENT_SECRET_EU }}
          BLIZZARD_CLIENT_ID_US:     ${{ secrets.BLIZZARD_CLIENT_ID_US }}
          BLIZZARD_CLIENT_SECRET_US: ${{ secrets.BLIZZARD_CLIENT_SECRET_US }}
          REGION:                 ${{ matrix.region }}
        run: python sync_pvp.py

      # 5. commit back to dev
      - name: Commit & push results
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add achiev/region_*.lua
          git commit -m "PvP sync update for ${{ matrix.region }}" || echo "No changes to commit"
          # bring your dev branch up-to-date so push won’t be rejected:
          git fetch origin dev
          git rebase origin/dev
          git push --force-with-lease origin dev
